# Travis CI script
language: c

os:
- linux

sudo: false

services:
- docker

env:
- BUILD_TYPE=default
#- BUILD_TYPE=android
#- BUILD_TYPE=check-py
#- BUILD_TYPE=cmake

addons:
  apt:
    packages:
    - valgrind
    - git

before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew install binutils valgrind ; fi
- sudo apt-get -qq update
- wget https://protobuf.googlecode.com/svn/rc/protobuf-2.6.0.tar.gz
- tar xvfz protobuf-2.6.0.tar.gz
- cd protobuf-2.6.0
- ./configure && sudo make install
- cd ..
- sudo apt-get install  -y libcunit1 libcunit1-dev
- sudo apt-get install  -y uuid-dev
- sudo apt-get install  -y protobuf-compiler libprotobuf-dev libprotoc-dev
- git clone https://github.com/protobuf-c/protobuf-c
- cd protobuf-c
- ./autogen.sh
- make
- sudo make install
- cd ..
- export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
# Hand off to generated script for each BUILD_TYPE
script: ./ci_build.sh
