################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_PROTO-C "proto-c")
    if (NOT PC_PROTO-C_FOUND)
        pkg_check_modules(PC_PROTO-C "proto-c")
    endif (NOT PC_PROTO-C_FOUND)
    if (PC_PROTO-C_FOUND)
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_PROTO-C_INCLUDE_HINTS ${PC_PROTO-C_INCLUDE_DIRS} ${PC_PROTO-C_INCLUDE_DIRS}/*)
        set(PC_PROTO-C_LIBRARY_HINTS ${PC_PROTO-C_LIBRARY_DIRS} ${PC_PROTO-C_LIBRARY_DIRS}/*)
    endif(PC_PROTO-C_FOUND)
endif (NOT MSVC)

find_path (
    PROTO-C_INCLUDE_DIRS
    NAMES protobuf-c.h
    HINTS ${PC_PROTO-C_INCLUDE_HINTS}
)

find_library (
    PROTO-C_LIBRARIES
    NAMES proto-c
    HINTS ${PC_PROTO-C_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    PROTO-C
    REQUIRED_VARS PROTO-C_LIBRARIES PROTO-C_INCLUDE_DIRS
)
mark_as_advanced(
    PROTO-C_FOUND
    PROTO-C_LIBRARIES PROTO-C_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
